language: python
dist: xenial
env:
  global:
   - PATH=$HOME/.local/bin:$PATH
   - AWS_DEFAULT_REGION=us-east-1
   - secure: "sitNFpdiQMbxHJIXkxcUfpSbAIdl9+bFYZcP2nQgwA3CShwRp1bAq2kWUsrzFjPhs+yxX5O+VVokRR0qsLJwmoH0AggWdYKhpTu7iGLoypCggnHh6I0Kt6Vepn6EjjkgkCzg/N+9gmZ1ZgtZ1NRDNdidEbyaWNZ1SlGkCNd0bys="
   - secure: "rKQwYdFMnU/MSWDlqMWuE44Zg/3uHDkay2K0y1dPjGxaQ1OE7AL+6VabbMoQ3kV4kBkFqaVn4yd4XeGvzkoeMz97tTWRPgztpztC77O+aqSPvYPkMU+iZQCpzIEekPAo7e/XEnZsxWgo9Io6zFbJkdg4PhXISycx05cpZbTJkK8="

stages:
- test
- coverage
- name: deploy
  if: tag IS present

install:
- python setup.py develop
- pip install -r test-requirements.txt
script: ci/test.sh
after_success:
- ci/upload-coverage.sh

jobs:
  include:
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
  - python: "3.8"
  - python: pypy3
  - stage: coverage
    if: repo = gmr/flatdict
    python: "3.7"
    services: []
    script: ci/combine-coverage.sh
  - stage: deploy
    if: repo = gmr/flatdict
    python: "3.8"
    services: []
    install: true
    before_script: []
    script: true
    after_success: []
    deploy:
      provider: pypi
      user: crad
      distributions: sdist bdist_wheel
      on:
        all_branches: true
        tags: true
      password:
        secure: "s1oAkXrQ3V533S250UJ5Ycop+XOyMZdM5kn/pBmMe5SFU0RCdp3RK0/Sj9o4z4+Tn7AkPyoBw6zneftdmykClJKGNfFLyGpkpCPscEHztEDrd1fCTd55qphAOkWhdx3x17T3cjXvcvu9810y6ekgAoDx1Tw+Qi6AJ2VL+sCZzmI="
